
<a href="https://colab.research.google.com/github/Argentan/DMA_LAB2/blob/master/tutoriales/03_manejo_de_datos-pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Librería Pandas

Pandas es la librería más utilizada para la manipulación de datos, utiliza series y dataframes que son estructuras de datos columnares, de una o dos dimensiones.
### Pandas 2.0
[Lo nuevo en Pandas 2.0](https://https://www.datacamp.com/blog/pandas-2-what-is-new-and-top-tips?).

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

2.1.4

## Tutoriales
* [10 Minutes to Pandas](https://pandas.pydata.org/docs/user_guide/10min.html)
* [4 Faster Alternatives to Pandas](https://chengzhizhao.com/4-faster-pandas-alternatives-for-data-analysis/)
* [What’s New in Pandas 2.1](https://towardsdatascience.com/whats-new-in-pandas-2-1-d26c0b8314a)

## Series

Son columnas de datos con índices.

Una serie es una estructura de datos unidimensional que puede contener cualquier tipo de datos, incluyendo números, cadenas, booleanos, objetos y más. Se puede pensar en una serie como una columna en una tabla de datos, donde cada elemento en la serie tiene un índice único que lo identifica.

Algunas de las principales características y funcionalidades de las series en Pandas son:

* tienen un índice, que se puede especificar manualmente o se generará automáticamente a partir de la posición de los elementos en la serie.
* pueden contener cualquier tipo de datos, incluyendo números, cadenas, booleanos, objetos y más.
* se pueden manipular y transformar utilizando una variedad de métodos y funciones, incluyendo la selección, filtrado y agrupamiento de datos.
* se pueden combinar y fusionar con otras series y dataframes utilizando métodos como concat() y merge().
* se pueden visualizar y graficar utilizando la funcionalidad de trazado de Pandas.

In [ ]:
obj = pd.Series([4, 4, -5, 3])
obj

0    4
1    4
2   -5
3    3
dtype: int64

In [ ]:
animales = ['Tortuga', 'Zorro', 'Paloma', 'Elefante', "Zorro"]
tipo = ['reptil', 'mamífero', 'ave', 'mamífero', 'mamífero' ]

obj = pd.Series(tipo, index=animales)
obj

Tortuga       reptil
Zorro       mamífero
Paloma           ave
Elefante    mamífero
Zorro       mamífero
dtype: object

In [ ]:
animales = ['Tortuga', 'Zorro', 'Paloma', 'Elefante', "Zorro"]
tipo = ['reptil', 'mamífero', 'ave', 'mamífero', 'mamífero' ]
obj = pd.Series(tipo)
obj

0      reptil
1    mamífero
2         ave
3    mamífero
4    mamífero
dtype: object

In [ ]:
obj[2]

'ave'

In [ ]:
obj.index = animales
obj

Tortuga       reptil
Zorro       mamífero
Paloma           ave
Elefante    mamífero
Zorro       mamífero
dtype: object

In [ ]:
obj["Zorro"]

Zorro    mamífero
Zorro    mamífero
dtype: object

In [ ]:
obj[0]

<ipython-input-11-5c1757a95ba4>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[0]

'reptil'

In [ ]:
obj.sort_values()

Paloma           ave
Zorro       mamífero
Elefante    mamífero
Zorro       mamífero
Tortuga       reptil
dtype: object

In [ ]:
obj.sort_values()[0]

<ipython-input-13-0e8dd4a3e152>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj.sort_values()[0]

'ave'

In [ ]:
obj.sort_values()["Zorro"]

Zorro    mamífero
Zorro    mamífero
dtype: object

In [ ]:
obj.sort_index()

Elefante    mamífero
Paloma           ave
Tortuga       reptil
Zorro       mamífero
Zorro       mamífero
dtype: object

In [ ]:
obj.sort_index()[0]

<ipython-input-16-10305df16db4>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj.sort_index()[0]

'mamífero'

In [ ]:
obj

Tortuga       reptil
Zorro       mamífero
Paloma           ave
Elefante    mamífero
Zorro       mamífero
dtype: object

## Data Frames

Son estructuras de dos dimensiones. Pueden pensarse como la concatenación horizontal de series.

`pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)`

In [ ]:
d = {'tipo_vivienda': ['casa', 'departamento'],
     'm2': [125, 59],
     'Barrio': ['San Martin', 'Florida'],
     'Precio (kUSD)': [200.52, 130.8]
    }
# df = pd.DataFrame(data=d, index=["casa1", "casa2"])
df = pd.DataFrame(data=d)
df

  tipo_vivienda   m2      Barrio  Precio (kUSD)
0          casa  125  San Martin         200.52
1  departamento   59     Florida         130.80

## Lectura de archivos de datos


Pandas soporta la lectura de una amplia cantidad de formatos ([más info](http://pandas.pydata.org/pandas-docs/stable/io.html)):

- read_csv
- read_excel
- read_hdf
- read_sql
- read_json
- read_msgpack (experimental)
- read_html
- read_gbq (experimental)
- read_stata
- read_sas
- read_clipboard
- read_pickle

Vamos a empezar con un dataset publicado para una competencia de Kaggle: [Titanic: Machine Learning from Disaster](https://www.kaggle.com/c/titanic/data).

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/pgaliana/IntroPythonCD/main/data/titanic_train.csv", index_col="PassengerId")
# data = pd.read_csv("https://raw.githubusercontent.com/pgaliana/IntroPythonCD/main/data/titanic_train.csv")

In [ ]:
data.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
data.tail()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
data.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
data.dtypes

Survived      int64
Pclass        int64
Name         object
Sex          object
Age         float64
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Cabin        object
Embarked     object
dtype: object

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object
 10  Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB

La función `describe()` proporciona una tabla con estadísticas descriptivas para las columnas numéricas del dataframe, incluyendo el número de observaciones, la media, la desviación estándar, los valores mínimo y máximo, y los cuartiles (25%, 50% y 75%).

Entre otras cosas, podemos ver:
* El número total de pasajeros en el conjunto de datos
* La edad promedio de los pasajeros
* La distribución de edades, medidas por los valores mínimo, máximo y los cuartiles
* La tarifa promedio pagada por los pasajeros
* La distribución de tarifas, medida por los valores mínimo, máximo y los cuartiles.

In [ ]:
data.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
data.shape

(891, 11)

In [ ]:
data.size

9801

In [ ]:
data.Pclass

PassengerId
1      3
2      1
3      3
4      1
5      3
      ..
887    2
888    1
889    3
890    1
891    3
Name: Pclass, Length: 891, dtype: int64

In [ ]:
data.Pclass.unique()

array([3, 1, 2])

In [ ]:
data.Pclass.value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
data.Pclass.nunique()

3

In [ ]:
data.Parch.unique()

array([0, 1, 2, 5, 3, 4, 6])

## Tipos de Indexado

Hay varias formas de seleccionar un subconjunto de los datos:

- Como las listas o arrays, por posición.
- Como los diccionarios, por clave o etiqueta.
- Como los arrays, por máscaras de verdadero o falso.
- Se puede indexar por número, rango o lista (array)
- Todos estos métodos pueden funcionar subconjunto como en las columnas


## Reglas Básicas

1. Se usan corchetes (abreviatura para el método `__getitem__`) para seleccionar columnas de un `DataFrame`

    ```python
    >>> df[['a', 'b', 'c']]
    ```

2. Se usa `.iloc` para indexar por posición (tanto filas como columnas)

    ```python
    >>> df.iloc[[1, 3], [0, 2]]
    ```
    
3. Se usa `.loc` para indexar por etiquetas (tanto filas como columnas)

    ```python
    >>> df.loc[["elemento1", "elemento2", "elemento3"], ["columna1", "columna2"]]
    ```

In [ ]:
# data.__getitem__("Name") == data["Name"]

In [ ]:
data["Name"]

PassengerId
1                                Braund, Mr. Owen Harris
2      Cumings, Mrs. John Bradley (Florence Briggs Th...
3                                 Heikkinen, Miss. Laina
4           Futrelle, Mrs. Jacques Heath (Lily May Peel)
5                               Allen, Mr. William Henry
                             ...
887                                Montvila, Rev. Juozas
888                         Graham, Miss. Margaret Edith
889             Johnston, Miss. Catherine Helen "Carrie"
890                                Behr, Mr. Karl Howell
891                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
data.loc[[1], ["Name", "Sex"]]

                                Name   Sex
PassengerId
1            Braund, Mr. Owen Harris  male

In [ ]:
data.loc[[1, 2, 3]]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [ ]:
data.loc[[1, 2, 3], "Age"]

PassengerId
1    22.0
2    38.0
3    26.0
Name: Age, dtype: float64

In [ ]:
data.loc[1, ["Name", "Sex", "Survived"]]

Name        Braund, Mr. Owen Harris
Sex                            male
Survived                          0
Name: 1, dtype: object

In [ ]:
temp = data.loc[:, ["Name", "Sex"]]
temp

                                                          Name     Sex
PassengerId
1                                      Braund, Mr. Owen Harris    male
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female
3                                       Heikkinen, Miss. Laina  female
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
5                                     Allen, Mr. William Henry    male
...                                                        ...     ...
887                                      Montvila, Rev. Juozas    male
888                               Graham, Miss. Margaret Edith  female
889                   Johnston, Miss. Catherine Helen "Carrie"  female
890                                      Behr, Mr. Karl Howell    male
891                                        Dooley, Mr. Patrick    male

[891 rows x 2 columns]

In [ ]:
temp.loc[1, "Name"] = "Rafa"
temp

                                                          Name     Sex
PassengerId
1                                                         Rafa    male
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female
3                                       Heikkinen, Miss. Laina  female
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
5                                     Allen, Mr. William Henry    male
...                                                        ...     ...
887                                      Montvila, Rev. Juozas    male
888                               Graham, Miss. Margaret Edith  female
889                   Johnston, Miss. Catherine Helen "Carrie"  female
890                                      Behr, Mr. Karl Howell    male
891                                        Dooley, Mr. Patrick    male

[891 rows x 2 columns]

In [ ]:
data.loc[1, "Name"], temp.loc[1, "Name"]

('Braund, Mr. Owen Harris', 'Rafa')

In [ ]:
temp = data.copy()
temp.index = ["pasajero_nro_" + str(i) for i in temp.index]
temp.index.name = data.index.name
temp

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
pasajero_nro_1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
pasajero_nro_2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
pasajero_nro_3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
pasajero_nro_4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
pasajero_nro_5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
pasajero_nro_887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
pasajero_nro_888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
pasajero_nro_889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
pasajero_nro_890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
pasajero_nro_891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
data.loc[1]

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Sex                            male
Age                            22.0
SibSp                             1
Parch                             0
Ticket                    A/5 21171
Fare                           7.25
Cabin                           NaN
Embarked                          S
Name: 1, dtype: object

In [ ]:
#data.loc["1"]

In [ ]:
temp.loc["pasajero_nro_1"]

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Sex                            male
Age                            22.0
SibSp                             1
Parch                             0
Ticket                    A/5 21171
Fare                           7.25
Cabin                           NaN
Embarked                          S
Name: pasajero_nro_1, dtype: object

In [ ]:
temp.loc[["pasajero_nro_1", "pasajero_nro_10", "pasajero_nro_800"], ["Name", "Sex"]]

                                                               Name     Sex
PassengerId
pasajero_nro_1                              Braund, Mr. Owen Harris    male
pasajero_nro_10                 Nasser, Mrs. Nicholas (Adele Achem)  female
pasajero_nro_800  Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...  female

In [ ]:
temp.iloc[[0, 1, 2], [2, 3]]

                                                             Name     Sex
PassengerId
pasajero_nro_1                            Braund, Mr. Owen Harris    male
pasajero_nro_2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
pasajero_nro_3                             Heikkinen, Miss. Laina  female

In [ ]:
del temp

In [ ]:
data.loc[:3, :"Name"]

,Survived,Pclass,Name
PassengerId,,,
1,0,3,"Braund, Mr. Owen Harris"
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
3,1,3,"Heikkinen, Miss. Laina"

In [ ]:
data.sort_values("Name").loc[:3]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.550,NaN,S
747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.250,NaN,S
280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.250,NaN,S
309,0,2,"Abelson, Mr. Samuel",male,30.0,1,0,P/PP 3381,24.000,NaN,C
875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.000,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
821,1,1,"Hays, Mrs. Charles Melville (Clara Jennings Gr...",female,52.0,1,1,12749,93.500,B69,S
275,1,3,"Healy, Miss. Hanora ""Nora""",female,NaN,0,0,370375,7.750,NaN,Q
805,1,3,"Hedman, Mr. Oskar Arvid",male,27.0,0,0,347089,6.975,NaN,S
655,0,3,"Hegarty, Miss. Hanora ""Nora""",female,18.0,0,0,365226,6.750,NaN,Q
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,NaN,S

## Cálculo de columnas nuevas

In [ ]:
temp = data[["Name"]].copy()
temp['OtroNombre'] = ["OTRO_" + n for n in data.Name]
temp

,Name,OtroNombre
PassengerId,,
1,"Braund, Mr. Owen Harris","OTRO_Braund, Mr. Owen Harris"
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...","OTRO_Cumings, Mrs. John Bradley (Florence Brig..."
3,"Heikkinen, Miss. Laina","OTRO_Heikkinen, Miss. Laina"
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)","OTRO_Futrelle, Mrs. Jacques Heath (Lily May Peel)"
5,"Allen, Mr. William Henry","OTRO_Allen, Mr. William Henry"
...,...,...
887,"Montvila, Rev. Juozas","OTRO_Montvila, Rev. Juozas"
888,"Graham, Miss. Margaret Edith","OTRO_Graham, Miss. Margaret Edith"
889,"Johnston, Miss. Catherine Helen ""Carrie""","OTRO_Johnston, Miss. Catherine Helen ""Carrie"""
890,"Behr, Mr. Karl Howell","OTRO_Behr, Mr. Karl Howell"
891,"Dooley, Mr. Patrick","OTRO_Dooley, Mr. Patrick"

In [ ]:
temp.OtroNombre[:10]

PassengerId
1                          OTRO_Braund, Mr. Owen Harris
2     OTRO_Cumings, Mrs. John Bradley (Florence Brig...
3                           OTRO_Heikkinen, Miss. Laina
4     OTRO_Futrelle, Mrs. Jacques Heath (Lily May Peel)
5                         OTRO_Allen, Mr. William Henry
6                                 OTRO_Moran, Mr. James
7                          OTRO_McCarthy, Mr. Timothy J
8                   OTRO_Palsson, Master. Gosta Leonard
9     OTRO_Johnson, Mrs. Oscar W (Elisabeth Vilhelmi...
10             OTRO_Nasser, Mrs. Nicholas (Adele Achem)
Name: OtroNombre, dtype: object

In [ ]:
# Borrar temp
del temp

### Filtrado

In [ ]:
# Filtrar registros cuya columna SibSp tiene valor > 0
# sibsp: Number of Siblings/Spouses Aboard
data["SibSp"] > 0

PassengerId
1       True
2       True
3      False
4       True
5      False
       ...
887    False
888    False
889     True
890    False
891    False
Name: SibSp, Length: 891, dtype: bool

In [ ]:
data.tail()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
# crear un dataframe de máscara (valores lógicos) considerando columna Age > 18
mask = data["Age"] > 18
mask

PassengerId
1       True
2       True
3       True
4       True
5       True
       ...
887     True
888     True
889    False
890     True
891     True
Name: Age, Length: 891, dtype: bool

In [ ]:
# Aplicar la máscara (filtrar) al dataframe data
data[mask]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# Seleccionar las columnas con tipo de dato float
data.select_dtypes("float")

              Age     Fare
PassengerId
1            22.0   7.2500
2            38.0  71.2833
3            26.0   7.9250
4            35.0  53.1000
5            35.0   8.0500
...           ...      ...
887          27.0  13.0000
888          19.0  30.0000
889           NaN  23.4500
890          26.0  30.0000
891          32.0   7.7500

[891 rows x 2 columns]

### Funciones comunes

Pandas tiene varias funciones incorporadas, por ejemplo:

* sum
* mean
* std
* var
* cumsum
* value_counts()

In [ ]:
# Calcular la media de edad (Age) de todo el dataset
data.Age.mean()

29.69911764705882

In [ ]:
# Calcular las medias de todas las columnas numéricas
data.mean(numeric_only=True)

Survived     0.383838
Pclass       2.308642
Age         29.699118
SibSp        0.523008
Parch        0.381594
Fare        32.204208
dtype: float64

In [ ]:
# Calcular las sumas de todas las columnas numéricas
data.sum(numeric_only=True)

Survived      342.0000
Pclass       2057.0000
Age         21205.1700
SibSp         466.0000
Parch         340.0000
Fare        28693.9493
dtype: float64

In [ ]:
# Mostrar columnas de tipo float
data.select_dtypes("float")

              Age     Fare
PassengerId
1            22.0   7.2500
2            38.0  71.2833
3            26.0   7.9250
4            35.0  53.1000
5            35.0   8.0500
...           ...      ...
887          27.0  13.0000
888          19.0  30.0000
889           NaN  23.4500
890          26.0  30.0000
891          32.0   7.7500

[891 rows x 2 columns]

In [ ]:
# Sumar los valores de las columnas de tipo float
data.select_dtypes("float").sum(axis=1)

PassengerId
1       29.2500
2      109.2833
3       33.9250
4       88.1000
5       43.0500
         ...
887     40.0000
888     49.0000
889     23.4500
890     56.0000
891     39.7500
Length: 891, dtype: float64

In [ ]:
# Calcular la suma acumulativa de la columna Age
data.Age.cumsum()

PassengerId
1         22.00
2         60.00
3         86.00
4        121.00
5        156.00
         ...
887    21128.17
888    21147.17
889         NaN
890    21173.17
891    21205.17
Name: Age, Length: 891, dtype: float64

In [ ]:
# Calcular, por cada columna, la suma de valores nulos
data.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [ ]:
# Por cada valor único de Survived, contar la cantidad de ocurrencias
data.Survived.value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
# Por cada valor único de Survived, contar la cantidad de ocurrencias normalizadas
data.Survived.value_counts(True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [ ]:
# Otra manera de hacer lo anterior
data.Survived.value_counts(1)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

### Ejercicios

1. Mostrar las primeras 16 filas del dataframe

In [ ]:
data.head(16)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S


2. ¿Cómo se llama el pasajero 881?

In [ ]:
nombre = data.loc[881, 'Name']
print("El nombre del pasajero con PassengerId igual a 881 es:", nombre)

3. Mostrar el nombre y el sexo de los pasajeros con PassengerId 881 y 456.

In [ ]:
data.loc[[881, 456], ["Name", "Sex"]]

4. Calcular una columna numFam que sea la suma de la cantidad de familiares en el barco.

SibSp - Number of Siblings/Spouses Aboard

Parch - Number of Parents/Children Aboard

In [ ]:
# Calcular la columna numFam como la suma de SibSp y Parch
data['numFam'] = data['SibSp'] + data['Parch']

# Mostrar las primeras cinco filas del DataFrame con la nueva columna numFam
print(data.head())

5. Mostrar el nombre y la edad de los sobrevivientes.

In [ ]:
data.loc[data.Survived == 1, ['Name', 'Age']]

5. Encontrar la edad media de los sobrevivientes.

In [ ]:
mask_survived = data['Survived'] == 1
mask_survived

In [ ]:
# Calcular la edad media de los sobrevivientes
edad_media_sobrevivientes = data[mask_survived]['Age'].mean()

# Mostrar la edad media de los sobrevivientes
print("La edad media de los sobrevivientes es:", edad_media_sobrevivientes)